name: Sokdak-AI-API

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sokdak-api-prod
    ports:
      - "${API_PORT}:8001"
    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8001
    env_file:
      - .env.prod
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:7
    container_name: sokdak-mongo-prod
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - sokdak-mongo-data-prod:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: sokdak-redis-prod
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

volumes:
  sokdak-mongo-data-prod: